options:
  size: "1x"

image: node:16

pipelines:
  branches:
    pull-requests:
      - step:
          name: "Test"
          # max-time: 10
          # size: "1x"
          script:
            - echo "Testing..."
          trigger: automatic
    master:
      - step:
          name: "Deploy Production"
          script:
            - npm ci --production
            - npm run build
          artifacts:
            - build
      - step:
          name: "Deploy Production"
          image: atlassian/pipelines-awscli
          caches:
            - docker
          services:
            - docker
          script:
            # ecr login
            - eval $(aws ecr get-login --no-include-email --region eu-west-2)
            # build and push docker image
            - docker build -t "175837576321.dkr.ecr.eu-west-2.amazonaws.com/auth:$BITBUCKET_BUILD_NUMBER" .
            - docker push "175837576321.dkr.ecr.eu-west-2.amazonaws.com/auth:$BITBUCKET_BUILD_NUMBER"
            # AWS deploy using cloudformation template
            - aws cloudformation deploy --template-file "cloudformation.yaml" --stack-name "Auth-Production" --parameter-overrides EncryptionKey=$EncryptionKey Environment="Production" ImageURI=175837576321.dkr.ecr.eu-west-2.amazonaws.com/auth:$BITBUCKET_BUILD_NUMBER
          trigger: manual
