Transform: AWS::Serverless-2016-10-31

Parameters:
  ImageURI:
    Type: String
  EncryptionKey:
    Type: String
    NoEcho: true
  Environment:
    Type: String

Conditions:
  IS_PRODUCTION:
    Fn::Equals:
      - !Ref Environment
      - "production"

Resources:
  AuthServer:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Timeout: 300
      ImageUri: !Ref ImageURI
      MemorySize: 512
      FunctionUrlConfig:
        AuthType: NONE
      Environment:
        Variables:
          NODE_ENV: !Ref Environment
          ENCRYPTION_KEY: !Ref EncryptionKey
