Transform: AWS::Serverless-2016-10-31

Parameters:
  ImageURI:
    Type: String
  EncryptionKey:
    Type: String
    NoEcho: true
  Environment:
    Type: String

Conditions:
  IS_PRODUCTION:
    Fn::Equals:
      - !Ref Environment
      - "production"

Resources:
  AuthServer:
    Type: AWS::Lambda::Function
    Properties:
      PackageType: Image
      Timeout: 300
      ImageUri: !Ref ImageURI
      MemorySize: 512
      Environment:
        Variables:
          NODE_ENV: !Ref Environment
          ENCRYPTION_KEY: !Ref EncryptionKey
      Events:
        - http:
            Path: /
            Method: ANY
            cors: true
        - http:
            path: /{proxy+}
            method: ANY
            cors: true
