version: "3"
services:
  app:
    container_name: "auth"
    build: .
    environment:
      NODE_ENV: "production"
    ports:
      # - "9000:8080" # for Testing Lambda
      - "5000:5000" # for Dev
